name: Build and deploy Node.js app assets to blob storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Build website
      run: |
        npm install
        npm run build

    - name: Deploy to Azure Storage
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        source-path: remote/build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}